; Place to: /etc/supervisor/conf.d/mosure-queue.conf

[program:mosure-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /root/www/mosure/artisan queue:work --sleep=3 --tries=3 --timeout=120
directory=/root/www/mosure
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/root/www/mosure/storage/logs/supervisor-queue.log
stopwaitsecs=3600
