; Optional: use supervisor to keep schedule:work alive
; If you choose crontab schedule:run, do not enable this file.
; Place to: /etc/supervisor/conf.d/mosure-scheduler.conf

[program:mosure-scheduler]
command=/usr/bin/php /root/www/mosure/artisan schedule:work
directory=/root/www/mosure
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/root/www/mosure/storage/logs/supervisor-scheduler.log
